version: '4'
services:
  magasy-db:
    image: postgres:13-alpine
    restart: always
    container_name: magasy-db
    volumes:
      - magasy-db-data:/var/lib/postgresql/data  # Ajout du volume pour la persistance des données
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - magasy-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - magasy-network

networks:
  magasy-network:
    driver: bridge

volumes:
  magasy-db-data:
    driver: local
